### ISSUE TITLE
end of life plans

### ISSUE THREAD

**Issue by zvictor** [albertcht/python-gcs-image#3]
With the end of life of Python 2 planned for January 1st and Google recommending (but not forcing yet) a migration, it seems to be time to start planning a replacement to this project.

![Image of Google comment on the deprecation of python 2](https://storage.googleapis.com/smartninja/google-deprecating-gae-answer-1548356137.png)

Is there any project based on app engine's [ServingUrl](https://cloud.google.com/appengine/docs/standard/go/images/reference#ServingURL) in an environment not about to be deprecated? 💾

**Comment by albertcht** [comment]
Hi @zvictor ,

Thanks for your reminding, it seems Python 2 is not going to be abandoned in the short term by Google.

But I will try to migrate this project to a Go version someday.
